org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.249
neo_version_range=[21.1.249,21.2)
loader_version_range=[4,)

mod_id=tsa_anticheat
mod_name=TSA Anticheat
mod_version=1.3.0
mod_group_id=com.zaremate.tsa_anticheat
mod_authors=ZareMate
mod_description=Reports client resource packs and mods using SHA-256 and provides packet-integrity checks with optional Admin Notes integration.
