modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="tsa_anticheat"
version="1.2.0"
displayName="TSA Anticheat"
authors="ZareMate"
description='''Verifies client resource packs and mods using SHA-256 content hashes and provides packet integrity checks with Discord webhook and permission-based broadcasts.'''

[[dependencies.tsa_anticheat]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.249,21.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tsa_anticheat]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
